# 3_plotmakers/plot_config.py

hists = {

    "dilepton_m": {
        "output": "dilepton_m",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 100,
        "ymin": 0,
        "ymax": 2000,
        "xtitle": "m(dilepton) (GeV)",
        "ytitle": "Events",
    },

    "dilepton_p": {
        "output": "dilepton_p",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 60,
        "ymin": 0,
        "ymax": 2000,
        "xtitle": "p(dilepton) (GeV)",
        "ytitle": "Events",
    },

    "lep0_p": {
        "output": "lep0_p",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 100,
        "ymin": 0,
        "ymax": 2000,
        "xtitle": "p(leading lepton) (GeV)",
        "ytitle": "Events",
    },

    "lep1_p": {
        "output": "lep1_p",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 100,
        "ymin": 0,
        "ymax": 2000,
        "xtitle": "p(subleading lepton) (GeV)",
        "ytitle": "Events",
    },

    "lep0_pt": {
        "output": "lep0_pt",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 70,
        "ymin": 0,
        "ymax": 300,
        "xtitle": "p_{T}(leading lepton) (GeV)",
        "ytitle": "Events",
    },

    "lep1_pt": {
        "output": "lep1_pt",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": 0,
        "xmax": 70,
        "ymin": 0,
        "ymax": 300,
        "xtitle": "p_{T}(subleading lepton) (GeV)",
        "ytitle": "Events",
    },

    "lep0_eta": {
        "output": "lep0_eta",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": -3,
        "xmax": 3,
        "ymin": 0,
        "ymax": 60,
        "xtitle": "#eta(leading lepton)",
        "ytitle": "Events",
    },

    "lep1_eta": {
        "output": "lep1_eta",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": -3,
        "xmax": 3,
        "ymin": 0,
        "ymax": 60,
        "xtitle": "#eta(subleading lepton)",
        "ytitle": "Events",
    },

    "lep0_phi": {
        "output": "lep0_phi",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": -5,
        "xmax": 5,
        "ymin": 0,
        "ymax": 60,
        "xtitle": "#phi(leading lepton) (rad)",
        "ytitle": "Events",
    },

    "lep1_phi": {
        "output": "lep1_phi",
        "logy": False,
        "stack": True,
        "rebin": 5,
        "xmin": -5,
        "xmax": 5,
        "ymin": 0,
        "ymax": 60,
        "xtitle": "#phi(subleading lepton) (rad)",
        "ytitle": "Events",
    },
}